### ISSUE TITLE
Please add the followings to the tasks/proxysql.yml

### ISSUE THREAD

**Issue by csabapatyi** [leucos/ansible-proxysql#2]
Hi,

First of all thanks for your work. I was wondering if you can make some modifications. 
- installing **python-mysqldb** next to mysql-common and mysql-client. It will enable users to use all the Ansible ProxySQL modules (http://docs.ansible.com/ansible/latest/list_of_database_modules.html)

Plus you are creating the /etc/proxysql.cnf with proper values, but those are not loading into the ProxySQL runtime layer actually (at lest for me). For that I had to add the following tasks:

```
    - name: Load the ProxySQL MYSQL USERS configuration from the config file to memory
      proxysql_manage_config:
        action: LOAD
        config_layer: CONFIG
        config_settings: MYSQL USERS
        direction: FROM
        login_user: "{{ proxysql_admin_user }}"
        login_password: "{{ proxysql_admin_password }}"
      tags:
        - configure_proxysql

    - name: Load the ProxySQL MYSQL USERS configuration from the config file to memory
      proxysql_manage_config:
        action: LOAD
        config_layer: MEMORY
        config_settings: MYSQL USERS
        direction: FROM
        login_user: "{{ proxysql_admin_user }}"
        login_password: "{{ proxysql_admin_password }}"
      tags:
        - configure_proxysql

    - name: Load the ProxySQL MYSQL SERVERS configuration from the config file to memory
      proxysql_manage_config:
        action: LOAD
        config_layer: CONFIG
        config_settings: MYSQL SERVERS
        direction: FROM
        login_user: "{{ proxysql_admin_user }}"
        login_password: "{{ proxysql_admin_password }}"
      tags:
        - configure_proxysql

    - name: Load the ProxySQL MYSQL SERVERS configuration from the config file to memory
      proxysql_manage_config:
        action: LOAD
        config_layer: MEMORY
        config_settings: MYSQL SERVERS
        direction: FROM
        login_user: "{{ proxysql_admin_user }}"
        login_password: "{{ proxysql_admin_password }}"
      tags:
        - configure_proxysql
```

If you want  I can create a pull request for these modifications as well.
